ANNOTATION_CI_COMMIT_REF = 'ci.itlabs.io/commit-ref'
ANNOTATION_CI_JOB_REF = 'ci.itlabs.io/job-ref'
ANNOTATION_CI_JOB_AUTHOR = 'ci.itlabs.io/job-author'
ANNOTATION_CI_REPO_URL = 'ci.itlabs.io/repo-url'
ANNOTATION_CI_PROJECT_ID = 'ci.itlabs.io/gl-project-id'
ANNOTATION_CI_COMMIT_BRANCH = 'ci.itlabs.io/commit-branch'
ANNOTATION_CI_COMMIT_TAG = 'ci.itlabs.io/commit-tag'
