# deployer specific variables
KUBE_NAMESPACE_ENV_VAR = 'KUBE_NAMESPACE'
KUBE_URL_ENV_VAR = 'KUBE_URL'
KUBE_TOKEN_ENV_VAR = 'KUBE_TOKEN'
ENVIRONMENT_ENV_VAR = 'ENVIRONMENT'
MANIFEST_FOLDER_ENV_VAR = 'MANIFEST_FOLDER'
SHOW_MANIFESTS_ENV_VAR = 'SHOW_MANIFESTS'

KUBE_VERBOSITY_ENV_VAR = 'KUBE_VERBOSITY'
KUBE_VERBOSITY_BASE = 10

VAULT_URL_ENV_VAR = 'VAULT_URL'
VAULT_APPROLE_ID_ENV_VAR = 'VAULT_APPROLE_ID'
VAULT_APPROLE_SECRET_ENV_VAR = 'VAULT_APPROLE_SECRET'
VAULT_SECRETS_PREFIX_ENV_VAR = 'VAULT_SECRETS_PREFIX'

# gitlab-ci specific variables
GITLAB_USER_ID_ENV_VAR = 'GITLAB_USER_ID'
GITLAB_USER_EMAIL_ENV_VAR = 'GITLAB_USER_EMAIL'
CI_PROJECT_ID_ENV_VAR = 'CI_PROJECT_ID'
CI_PROJECT_DIR_ENV_VAR = 'CI_PROJECT_DIR'
CI_PROJECT_URL_ENV_VAR = 'CI_PROJECT_URL'
CI_COMMIT_SHA_ENV_VAR = 'CI_COMMIT_SHA'
CI_COMMIT_REF_NAME_ENV_VAR = 'CI_COMMIT_REF_NAME'
CI_COMMIT_BRANCH_ENV_VAR = 'CI_COMMIT_BRANCH'
CI_COMMIT_TAG_ENV_VAR = 'CI_COMMIT_TAG'
CI_RUNNER_TAGS_ENV_VAR = 'CI_RUNNER_TAGS'
CI_JOB_ID_ENV_VAR = 'CI_JOB_ID'
CI_JOB_URL_ENV_VAR = 'CI_JOB_URL'
CI_PIPELINE_ID_ENV_VAR = 'CI_PIPELINE_ID'
CI_REGISTRY_ENV_VAR = 'CI_REGISTRY'

TRIVY_IMAGE_TEMPLATE_ENV_VAR = 'TRIVY_IMAGE_TEMPLATE'

DEPLOY_WAIT_TIMEOUT_ENV_VAR = 'DEPLOY_WAIT_TIMEOUT'
